apiVersion: v2
annotations:
  charts.openshift.io/name: wavefront
name: wavefront
description: Wavefront Collector for Kubernetes
kubeVersion: ">= 1.17.0"
appVersion: 1.7.4
version: 1.7.6
keywords:
- metric
- monitoring
- observability
- alerting
home: https://www.wavefront.com
sources:
- https://github.com/wavefrontHQ/wavefront-collector-for-kubernetes
- https://github.com/wavefrontHQ/wavefront-proxy
maintainers:
  - name: johncornish
    email: jcornish@vmware.com
  - name: josephgee
    email: jgee@vmware.com
  - name: mceldeen
    email: matthewco@vmware.com
  - name: mmichael
    email: mamichael@vmware.com
